//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosticData) DeepCopyInto(out *DiagnosticData) {
	*out = *in
	if in.RSSDissection != nil {
		in, out := &in.RSSDissection, &out.RSSDissection
		*out = new(RSSDissection)
		**out = **in
	}
	if in.LastLogLines != nil {
		in, out := &in.LastLogLines, &out.LastLogLines
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosticData.
func (in *DiagnosticData) DeepCopy() *DiagnosticData {
	if in == nil {
		return nil
	}
	out := new(DiagnosticData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCrashReport) DeepCopyInto(out *PodCrashReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCrashReport.
func (in *PodCrashReport) DeepCopy() *PodCrashReport {
	if in == nil {
		return nil
	}
	out := new(PodCrashReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodCrashReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCrashReportList) DeepCopyInto(out *PodCrashReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodCrashReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCrashReportList.
func (in *PodCrashReportList) DeepCopy() *PodCrashReportList {
	if in == nil {
		return nil
	}
	out := new(PodCrashReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodCrashReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCrashReportSpec) DeepCopyInto(out *PodCrashReportSpec) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCrashReportSpec.
func (in *PodCrashReportSpec) DeepCopy() *PodCrashReportSpec {
	if in == nil {
		return nil
	}
	out := new(PodCrashReportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCrashReportStatus) DeepCopyInto(out *PodCrashReportStatus) {
	*out = *in
	in.Diagnostics.DeepCopyInto(&out.Diagnostics)
	if in.NotifiedAt != nil {
		in, out := &in.NotifiedAt, &out.NotifiedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCrashReportStatus.
func (in *PodCrashReportStatus) DeepCopy() *PodCrashReportStatus {
	if in == nil {
		return nil
	}
	out := new(PodCrashReportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RSSDissection) DeepCopyInto(out *RSSDissection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RSSDissection.
func (in *RSSDissection) DeepCopy() *RSSDissection {
	if in == nil {
		return nil
	}
	out := new(RSSDissection)
	in.DeepCopyInto(out)
	return out
}
