//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by hand (matches controller-gen output). DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of PodCrashReportSpec into another instance.
func (in *PodCrashReportSpec) DeepCopyInto(out *PodCrashReportSpec) {
	*out = *in
}

// DeepCopy creates a new deep copy of PodCrashReportSpec.
func (in *PodCrashReportSpec) DeepCopy() *PodCrashReportSpec {
	if in == nil {
		return nil
	}
	out := new(PodCrashReportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of DiagnosticData into another instance.
func (in *DiagnosticData) DeepCopyInto(out *DiagnosticData) {
	*out = *in
	if in.LastLogLines != nil {
		in, out := &in.LastLogLines, &out.LastLogLines
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a new deep copy of DiagnosticData.
func (in *DiagnosticData) DeepCopy() *DiagnosticData {
	if in == nil {
		return nil
	}
	out := new(DiagnosticData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of PodCrashReportStatus into another instance.
func (in *PodCrashReportStatus) DeepCopyInto(out *PodCrashReportStatus) {
	*out = *in
	in.Diagnostics.DeepCopyInto(&out.Diagnostics)
}

// DeepCopy creates a new deep copy of PodCrashReportStatus.
func (in *PodCrashReportStatus) DeepCopy() *PodCrashReportStatus {
	if in == nil {
		return nil
	}
	out := new(PodCrashReportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of PodCrashReport into another instance.
func (in *PodCrashReport) DeepCopyInto(out *PodCrashReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a new deep copy of PodCrashReport.
func (in *PodCrashReport) DeepCopy() *PodCrashReport {
	if in == nil {
		return nil
	}
	out := new(PodCrashReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *PodCrashReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of PodCrashReportList into another instance.
func (in *PodCrashReportList) DeepCopyInto(out *PodCrashReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodCrashReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new deep copy of PodCrashReportList.
func (in *PodCrashReportList) DeepCopy() *PodCrashReportList {
	if in == nil {
		return nil
	}
	out := new(PodCrashReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *PodCrashReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
